config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  
  get '/home', to: 'pages#home'
  get '/splash', to:'pages#splash'
  
  resources :events do
    member do
      get 'favorite'
      get 'ticket'
    end
  end
  
  resources :users, except:[:new]
  
  get '/register', to: 'users#new'
  
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"
  
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  has_many :favorites
  has_many :tickets
  validates :user_id, presence: true
  validates :name, presence: true, length: {minimum: 5, maximum: 100}
  validates :description, presence: true, length: {minimum: 1, maximum: 500}
  validates :address, presence: false, length: {minimum: 0, maximum: 200}
  validates :price, presence: true
  validates :start_date, presence: true
  mount_uploader :picture, PictureUploader
  validate :picture_size
  
  def status
    self.favorites.where(favorite: true).size
  end
  
  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5mb")
      end
    end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
   belongs_to :user
   belongs_to :event
   
   validates_uniqueness_of :user, scope: :event
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :event
  
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
   belongs_to :user
   belongs_to :event
   
   validates_uniqueness_of :user, scope: :event
end

app/models/user.rb
class User < ActiveRecord::Base
   has_many :events
   has_many :favorites
   has_many :tickets
    before_save {self.email = email.downcase}
    validates :name, presence: true, length: {minimum: 2, maximum:40}
    validates :last_names, presence: true, length: {minimum: 2, maximum:40}
    validates :password, presence: true, length: {minimum: 5, maximum:30}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 105},
                                        uniqueness: {case_sensitive: false},
                                        format:{with: VALID_EMAIL_REGEX}
    has_secure_password 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in? 
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to :back
    end
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:edit, :update, :show, :favorite, :ticket]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update]
  
    def index
        @events = Event.all
    end
    
    def show
      
    end
    def new 
       @event = Event.new 
    end
    
    def create
        @event = Event.new(event_params)
        @event.user = current_user
        
        if @event.save
          flash[:success]= "Tu evento fue creado con éxito!"
          redirect_to events_path
        else
          render :new
        end
    end
    
    def edit
      
    end 
    
    def update 
      if @event.update(event_params)
        redirect_to event_path(@event)
      else
        render :edit
      end
    end 
    
    def favorite
      Favorite.create(favorite: params[:favorite], user: current_user, event: @event)
      redirect_to :back
    end
    
    def ticket
      Ticket.create(ticket: params[:ticket], user: current_user, event: @event)
      flash[:success]  = "Tu boleto fue comprado exitosamente" 
      redirect_to :back
    end
    
    private
    
      def event_params
        params.require(:event).permit(:name, :address, :description, :price, :start_date, :picture)
      end
      
      def set_event
        @event = Event.find(params[:id])
      end
      
      def require_same_user
        if current_user != @event.user
          flash[:danger]  = "You can only edit your own events" 
          redirect_to events_path
        end
      end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
   
   def new
       
   end
   
   def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
       session[:user_id] = user.id
       redirect_to events_path
   else
        flash.now[:danger] = "Your email address or password does not match"
        render 'new'
    end
   end
   
   def destroy
       session[:user_id] = nil
       redirect_to root_path
   end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to events_path if logged_in?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show, :like]
    before_action :require_same_user,only: [:edit, :update]
    
    
    def new
       @user = User.new 
    end
    
    def create
        @user = User.new(user_params) 
        if @user.save
            redirect_to events_path
        else
            render 'new'
        end
    end
    
    def edit
        
    end
    
    def update
        if @user.update(user_params)
            redirect_to user_path(@user)
        else
            render 'edit'
        end
    end
    
    def show
        
    end
    
    private
        def user_params
            params.require(:user).permit(:email, :name, :last_names, :phone, :password)
        end
        
        def set_user
            @user = User.find(params[:id])
        end
          
        def require_same_user
            if current_user != @user
              flash[:danger]  = "You can only edit your own profile" 
              redirect_to root_path
            end
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/edit.html.erb
<p>
<h1 style="text-align:center">Editar Evento</h1>
<hr/>
</p>
<% if @event.errors.any? %>
  <div class="row">
    <div class="alert alert-danger col-md-8 col-md-offset-2">
      <h5>Please correct the following errors:</h5>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </div>
  </div>
<% end %>
<div class="row">
    <div class="well col-md-8 col-md-offset-2">
        <%= form_for @event do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        
        <%= f.label :address %>
        <%= f.text_field :address %>
        
        <%= f.label :description %>
        <%= f.text_area :description, rows:7 %>
        
        <%= f.label :price %>
        <%= f.text_field :price %>
        
        <%= f.label :start_date %>
        <%= f.date_field :start_date %>
        
        <span class="picture">
          <%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/png' %>
        </span>
        
        <%= f.submit class:"btn btn-success" %>
        <% end %>
    </div>
</div>

<script type="text/javascript">
  $('#event_picture').bind('change', function(){
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5){
      alert('Maximum file size is 5MB. Please select a smaller file');
    }
  });
</script>

app/views/events/index.html.erb
<h1 style="text-align:center">Todos los Eventos</h1>

<% @events.each do |event| %>
    <div class="row">
        <div class="col-md-2">
            <section class="chef_info center">
                
            </section>
        </div>
        <div class="col-md-6 well">
            <div class="pull-right">
                <%= link_to favorite_event_path(event, favorite: true), method: :post do %>
                    <i style="font-size:20pt" class="glyphicon glyphicon glyphicon-star-empty"></i> &nbsp <%= event.status %>
                <% end %>
            </div>
            <h4><%= link_to event.name, event_path(event) %></h4>
            <p><%= event.description %></p>
            <p>
                <span class="quiet"><small><%= time_ago_in_words(event.created_at) %> ago</small></span>
            </p>
        </div>
        <div class="col-md-4">
            <%= image_tag(event.picture.url, size: "250x150", class: "gravatar") if event.picture? %>
        </div>
    </div>
    
<% end %>

app/views/events/new.html.erb
<p>
<h1 style="text-align:center">Crear un nuevo evento</h1>
<hr/>
</p>
<% if @event.errors.any? %>
  <div class="row">
    <div class="alert alert-danger col-md-8 col-md-offset-2">
      <h5>Please correct the following errors:</h5>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </div>
  </div>
<% end %>
<div class="row">
    <div class="well col-md-8 col-md-offset-2">
        <%= form_for(@event, html: {multipart: true}) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        
        <%= f.label :address %>
        <%= f.text_field :address %>
        
        <%= f.label :description %>
        <%= f.text_area :description, rows:7 %>
        
        <%= f.label :price %>
        <%= f.text_field :price %>
        
        <%= f.label :start_date %>
        <%= f.date_field :start_date %>
        
        <span class="picture">
          <%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/png' %>
        </span>
        
        <%= f.submit class:"btn btn-success" %>
        <% end %>
    </div>
</div>

<script type="text/javascript">
  $('#event_picture').bind('change', function(){
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5){
      alert('Maximum file size is 5MB. Please select a smaller file');
    }
  });
</script>

app/views/events/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h1><%= @event.name %></h1>
        </div>
        
        <div class="col-md-6">
            <% if logged_in? and @event.user == current_user %>
                <p><%= link_to "Editar evento", edit_event_path(@event), class: "btn btn-success pull-right" %></p>
            <% end %>
            <% if logged_in? and @event.user != current_user %>
                <p><%= link_to "Comprar boleto", ticket_event_path(@event, ticket: true), class: "btn btn-success pull-right" %></p>
            <% end %>
        </div>
        
    </div>
    <hr/>
    <div class="show_recipe">
        <%= image_tag(@event.picture.url, size: "250x150", class: "gravatar") if @event.picture? %>
    </div>
    <div class="well">
        <div class="pull-right">
            <%= link_to favorite_event_path(@event, favorite: true), method: :post do %>
                <i style="font-size:20pt" class="glyphicon glyphicon glyphicon-star-empty"></i> &nbsp <%= @event.status %>
            <% end %>
        </div>
        <h4>$<%= @event.price %></h4>
        <h4><%= simple_format(@event.description) %></h4>
        <h4><%= @event.address %></h4>
    </div>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
<div class="row">
    <div class="col-md-12">
        <% flash.each do |message_type, messge| %>
          <div class="alert alert-<%= message_type %>">
            <div class="row">
              <p class="col-md-11" style="text-align:center;"><%= messge %></p>
              <a class="close col-md-1" data-dismiss="alert">x</a>
            </div>
          </div>
        <% end %>
    </div>
</div>
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-default">
    <div class="container">
        <div class="row">
        <%= link_to "eventsapp", root_path, class:"btn btn-lg btn-warning", id:"logo"%>
        <% if logged_in? %>
          <div class="nav_item">
            <%= link_to "Nuevo Evento", new_event_path, class:"btn btn-success pull-right"%>
          </div>
          <div class="nav_item">
            <%= link_to "Ver Perfil", user_path(current_user), class:"btn btn-success"%>
          </div>
        <% end %>
        
        <div class="nav_item">
          <%= link_to "Todos los Eventos", events_path, class:"btn btn-success"%>
        </div>
        
        <% if logged_in? %>
          <div class="nav_item">
            <%= link_to "Cerrar Sesión", logout_path, class:"btn btn-danger pull-right"%>
          </div>
        <% end %>
      </div>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navigation' %>
<%= render 'layouts/messages' %>
<%= yield %>
</body>
</html>

app/views/logins/new.html.erb
<h1 style="text-align:center;">Iniciar Sesión</h1>
<hr/>
<div class="row">
    <div class="well col-md-6 col-md-offset-3">
        <%= form_tag '/login' do %>
            <%= label_tag :email %>
            <%= text_field_tag :email %>
            
            <%= label_tag :password %>
            <%= password_field_tag :password %>
            
            <%= submit_tag 'Login', class: "btn btn-success" %>
        <% end %> 
    </div>
</div>

app/views/pages/home.html.erb
<div class="container">
    <div class="well center" style="margin-top:20px;">
        <h1 style="text-align:center;">Bienvenidos a EventsApp</h1>
        <h3 style="text-align:center; margin-bottom:15px;"> Reg&iacute;strate y ent&eacute;rate de los mejores eventos!</h3>
        <%= link_to "¡Regístrate ya!", register_path, class: "btn btn-lg btn-success center" %>
        <p style="text-align:center; margin-top:15px;"><%= link_to "Inicia Sesión", login_path, class: "center" %></p>
    </div>
</div>

app/views/tickets/show.html.erb
ticket

app/views/users/edit.html.erb
<p>
<h1 style="text-align:center">Editar Perfil</h1>
<hr/>
</p>
<% if @user.errors.any? %>
  <div class="row">
    <div class="alert alert-danger col-md-8 col-md-offset-2">
      <h5>Please correct the following errors:</h5>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </div>
  </div>
<% end %>

<div class="row">
    <div class="well col-md-8 col-md-offset-2">
        <%= form_for @user do |f| %>
        <%= f.label :email %>
        <%= f.text_field :email %>
        
        <%= f.label :name %>
        <%= f.text_field :name %>
        
        <%= f.label :last_names %>
        <%= f.text_field :last_names, rows:7 %>
        
        <%= f.label :phone %>
        <%= f.text_field :phone %>
        
        <%= f.label :password %>
        <%= f.password_field :password %>
        
        <%= f.submit class:"btn btn-success" %>
        <% end %>
    </div>
</div>

app/views/users/new.html.erb
<p>
<h1 style="text-align:center">Crear un nuevo usuario</h1>
<hr/>
</p>
<% if @user.errors.any? %>
  <div class="row">
    <div class="alert alert-danger col-md-8 col-md-offset-2">
      <h5>Please correct the following errors:</h5>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </div>
  </div>
<% end %>

<div class="row">
    <div class="well col-md-8 col-md-offset-2">
        <%= form_for @user do |f| %>
        <%= f.label :email %>
        <%= f.text_field :email %>
        
        <%= f.label :name %>
        <%= f.text_field :name %>
        
        <%= f.label :last_names %>
        <%= f.text_field :last_names, rows:7 %>
        
        <%= f.label :phone %>
        <%= f.text_field :phone %>
        
        <%= f.label :password %>
        <%= f.password_field :password %>
        
        <%= f.submit class:"btn btn-success" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h1 style="text-align:center;"><%= @user.name %> <%= @user.last_names %></h1>
        </div>
        <hr/>
        <br><br><br>
        <div class="col-md-8 col-md-offset-2">
            <div class="well">
                <div class="row">
                    <div class="col-md-8">
                        <p><%= @user.email %></p>
                    </div>
                    <div class="col-md-4">
                        <p><%= link_to "Editar perfil", edit_user_path(@user), class: "btn btn-success pull-right" %></p>
                    </div>
                </div>
            </div>
            <div class="col-md-5">
            <h2 style="text-align:center;">Eventos de <%= @user.name %>:</h2>
            <% @user.events.each do |event| %>
                <div class="row">
                    <div class="col-md-12 well">
                        <div class="pull-right">
                            <%= link_to favorite_event_path(event, favorite: true), method: :post do %>
                                <i style="font-size:20pt" class="glyphicon glyphicon glyphicon-star-empty"></i> &nbsp <%= event.status %>
                            <% end %>
                        </div>
                        <h4><%= link_to event.name, event_path(event) %></h4>
                        <p><%= event.description %></p>
                        <p>
                            <span class="quiet"><small><%= time_ago_in_words(event.created_at) %> ago</small></span>
                        </p>
                    </div>
                </div>
            <% end %>
            </div>
            <div class="col-md-2"></div>
            <div class="col-md-5">
            <h2 style="text-align:center;">Boletos de <%= @user.name %>:</h2>
            <% @user.tickets.each do |ticket| %>
                <div class="row">
                    <div class="col-md-12 well">
                        <h4><%= Event.find(ticket.event_id).name %></h4>
                        <h5>Número de boleto: <%= ticket.id %></h5>
                    </div>
                </div>
            <% end %>
            </div>
        </div>
    </div>
    <hr/>
</div>